config/routes.rb
Rails.application.routes.draw do
  get 'blogs' => 'blog#index'
  get 'blogs/:id' => 'blog#show', as: 'blog'
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  post 'blogs' => 'blog#create'
  get 'blogs/:id/edit' => 'blog#edit', as: 'edit_blog'
  patch 'blogs/:id' => 'post#update'
  delete 'blogs/:id' => 'blog#destroy'

  root "blog#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blogs = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    if @blog.valid?
      redirect_to blogs_path
      end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      redirect_to blogs_path
    end
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
      if @blog.valid?
        redirect_to blog_path
      end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h3>Edit your blog</h3>
<%= form_with model: @blog do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
<br/>
  <%= form.label :content %>
  <%= form.text_field :content %>  
<br/>
  <%= form.submit 'Edit Blog' %>
<% end %>
<%= link_to 'Home', blogs_path %>

app/views/blog/index.html.erb
<h1>Links to our blogs!</h1>
<ul>
<% @blogs.each do |blog| %>
<li>  <%= link_to blog.title, blog_path(blog)%> </li>
<% end %>
</ul>
<%= link_to 'Add Blog!', new_blog_path%>

app/views/blog/new.html.erb
<h1> Submit New Blog! </h1>
<%= form_with model: @blog do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br>
  <%= form.submit:"Add Blog!" %>
<% end %>
<br>
<%= link_to 'Home', blogs_path %>

app/views/blog/show.html.erb
<h1>Blog Content</h1>
<br />
<%= @blogs.content %>
<br />

<p>
<%= link_to 'Delete this Blog', edit_blog_path, data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</p>
<p><%= link_to 'Edit this Blog', edit_blog_path %></p>
</p>
<%= link_to 'Home', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>